---
# add mariadb repository in Debian

- name: Add mariadb apt key
  apt_key:
    id: "{{ item }}"
    keyserver: keyserver.ubuntu.com
  with_items: "{{ debian_repository_id }}"

- name: Add mariadb repository for Debian
  apt_repository:
    repo: "{{ mariadb_debian_repository }}"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false
