---
# Upgrade Mariadb

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: "auto"

- name: Set mariadb_version fact
  set_fact:
    mariadb_version_server: "{{ ansible_facts.packages['mariadb-server'][0].version | regex_search('(?<=:)([0-9]+\\.[0-9]+\\.[0-9]+)') }}"

- name: Set common variables
  set_fact:
    mariadb_user: root
    mariadb_host: localhost

- name: stop replication MariaDB if condition met
  community.mysql.mysql_replication:
    mode: stopreplica
    login_host: "{{ mariadb_host }}"
    login_user: "{{ mariadb_user }}"
    config_file: "{{ mariadb_configuration_file }}"
    login_unix_socket: "{{ mariadb_socket }}"
  become: yes
  when: mariadb_version_server is version(mariadb_version, '<')

- name: Pin {{ mariadb_packages[0] }} version
  copy:
    dest: "/etc/apt/preferences.d/{{ mariadb_packages[0] }}"
    content: |
      Package: {{ mariadb_packages[0] }}
      Pin: version {{ mariadb_version_pin }}
      Pin-Priority: 1001
  become: true
  when: mariadb_version_pin is defined

- name: Update mariadb-server package
  apt:
    name: mariadb-server
    state: latest
  when: mariadb_version_server is version(mariadb_version, '<')
  register: upgrade_finish

- name: start replication MariaDB if upgraded
  community.mysql.mysql_replication:
    mode: startreplica
    login_host: "{{ mariadb_host }}"
    login_user: "{{ mariadb_user }}"
    config_file: "{{ mariadb_configuration_file }}"
    login_unix_socket: "{{ mariadb_socket }}"
  become: yes
  when: mariadb_version_server is version(mariadb_version, '<') and upgrade_finish is changed
